version: "3"
services:
  web:
    container_name: app_server
    build:
      context: ./app_server
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        LARAVEL_VERSION: ${LARAVEL_VERSION}
    volumes:
      - ./app_server/laravel/:/var/www/laravel
    depends_on:
      - db
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
    - docker_net

  db:
    container_name: mysql_server
    build: ./db_server
    volumes:
      - ./db_server/db_volume:/var/lib/mysql
      - ./db_server/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      TZ: 'Asia/Tokyo'
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge